### PR TITLE
Fix memory leaks and unsafety in FuturesUnordered

### PR DESCRIPTION
**Pull request by alexcrichton**
More details in the commits and comments.

### CODE REVIEW

**Comment by carllerche** [comment]
I still haven't dug deeply into this PR, but it does seem like it is a significant departure from the previous implementation.

I wrote a super quick benchmark to get an idea of how much the change would impact performance:

```rust
#[bench]
fn oneshots(b: &mut Bencher) {
    const NUM: usize = 10_000;

    b.iter(|| {
        let mut txs = VecDeque::with_capacity(NUM);
        let mut rxs = FuturesUnordered::new();

        for _ in 0..NUM {
            let (tx, rx) = oneshot::channel();
            txs.push_back(tx);
            rxs.push(rx);
        }

        thread::spawn(move || {
            while let Some(tx) = txs.pop_front() {
                let _ = tx.send("hello");
            }
        });

        future::lazy(move || {
            loop {
                if let Ok(Async::Ready(None)) = rxs.poll() {
                    return Ok::<(), ()>(());
                }
            }
        }).wait().unwrap();
    });
}
```

Original: 3,124,888 ns/iter
This PR: 4,203,149 ns/iter

So, the PR is ~25% slower, but the benchmark also includes a *lot* of setup "overhead" (creating the VecDeque, creating the oneshots, etc...)

Again, not super scientific yet and there would be value in having additional benchmarks to test more cases, **and** I have yet to look through the code in depth, but the perf hit is of concern to me.

Thoughts?

**Comment by alexcrichton** [comment]
Ok but we aren't talking about performance but about correctness? I don't mind optimizing more but we need to be correct first

**Comment by carllerche** [comment]
I mean, like I said this is a significant departure from the old code base, which would be fine, except to regain the lost performance, this avenue will most likely have to be abandoned. If this were a 100% safe path, that would be one thing, but I don't see how this buys much more in the way of safety.

Could you explain why you think this path will pan out performance wise. Otherwise, getting correctness doesn't seem worth it if performance tweaks will immediately result in reverting back.

**Comment by alexcrichton** [comment]
Ok, merged!

**Pull request closed without merging**
